# Site settings
title: (d)EATH (n)OTES
#logo: /images/logo.png
logo_text: dn
description: ~ Death is certain ~ Time of death is uncertain ~
baseurl:  # the subpath of your site, e.g. /blog
url: http://death-notes.net # the base hostname & protocol for your site

# Main header
header:
  text_shadow: 0 0 20px rgba(28, 47, 53, .8) # CSS text-shadow

# Navigation
navigation:
  - slug: /about
    label: about
  - slug: /resources
    label: resources

#
permalink: pretty

# Services (all are optional)
analytics: UA-86167762-1 # Google Analytics tracking ID
disqus: #jasper-theme    # Disqus shortname
facebook_l10n: en_US    # Your locale (en_US, fr_FR, etc.)
twitter:     # Website's Twitter username (without the '@')

# Build settings
# Reading Files
include:
  - _pages
exclude: [CNAME, Gemfile, Gemfile.lock]
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: true
      is_post: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      author_profile: false
      is_page: true
# Plugins
gems: [jekyll-paginate]
paginate: 5 # Post excerpts by page
paginate_path: "/page/:num" # Default was "/page:num/"
